backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "site/static/images/upload"
public_folder: "site/images/upload"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "quotes" # Used in routes, e.g., /admin/collections/blog
    label: "Quotes" # Used in the UI
    folder: "site/content/q" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter_views: 
      - field: "draft"
        pattern: true
        label: "Drafts"
      - field: "draft"
        pattern: false
        label: "Published"
    view_groups:
      - label: Author
        field: authors.*
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          "required": true,
          pattern:
            [
              "^[a-z0-9]+(?:-[a-z0-9]+)*$",
              "A slug can have no spaces or special characters",
            ],
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          minimize_collapsed: true,
          field: { label: Image, name: "image", widget: "string" },
        }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field:
          label: "Tag"
          name: "tag"
          widget: "relation"
          collection: "quotes"
          search_fields: ["tags.*.name"]
          display_fields: ["tags.*.name"]
          value_field: "tags.*.name"
      - {
          label: "Authors",
          name: "authors",
          widget: "list",
          allow_add: true,
          collapsed: false,
          field: { label: "Author", name: "author", widget: "string" },
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { "label": "Source URL", name: "source_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Draft", name: "draft", widget: "boolean" }
